// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcppOU
NumericMatrix rcppOU(NumericMatrix x, double theta, double mu, double dt, double sigma);
RcppExport SEXP _RTL_rcppOU(SEXP xSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP dtSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppOU(x, theta, mu, dt, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rcppOUJ
NumericMatrix rcppOUJ(NumericMatrix x, NumericMatrix djump, double theta, double mu, double dt, double sigma, double jump_prob, double jump_avesize);
RcppExport SEXP _RTL_rcppOUJ(SEXP xSEXP, SEXP djumpSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP dtSEXP, SEXP sigmaSEXP, SEXP jump_probSEXP, SEXP jump_avesizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type djump(djumpSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type jump_prob(jump_probSEXP);
    Rcpp::traits::input_parameter< double >::type jump_avesize(jump_avesizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppOUJ(x, djump, theta, mu, dt, sigma, jump_prob, jump_avesize));
    return rcpp_result_gen;
END_RCPP
}
// rcppOUt
NumericMatrix rcppOUt(NumericMatrix x, double theta, double dt, double sigma);
RcppExport SEXP _RTL_rcppOUt(SEXP xSEXP, SEXP thetaSEXP, SEXP dtSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppOUt(x, theta, dt, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RTL_rcppOU", (DL_FUNC) &_RTL_rcppOU, 5},
    {"_RTL_rcppOUJ", (DL_FUNC) &_RTL_rcppOUJ, 8},
    {"_RTL_rcppOUt", (DL_FUNC) &_RTL_rcppOUt, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RTL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
