# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CND <- function(x) {
    .Call(`_RTL_CND`, x)
}

gbs <- function(CallPutFlag, S, X, T, r, v) {
    .Call(`_RTL_gbs`, CallPutFlag, S, X, T, r, v)
}

rcppOU <- function(x, theta, mu, dt, sigma) {
    .Call(`_RTL_rcppOU`, x, theta, mu, dt, sigma)
}

rcppOUJ <- function(x, djump, theta, mu, dt, sigma, jump_prob, jump_avesize) {
    .Call(`_RTL_rcppOUJ`, x, djump, theta, mu, dt, sigma, jump_prob, jump_avesize)
}

rcppOUt <- function(x, theta, dt, sigma) {
    .Call(`_RTL_rcppOUt`, x, theta, dt, sigma)
}

