# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppOU <- function(x, theta, mu, dt, sigma) {
    .Call(`_RTL_rcppOU`, x, theta, mu, dt, sigma)
}

rcppOUt <- function(x, theta, dt, sigma) {
    .Call(`_RTL_rcppOUt`, x, theta, dt, sigma)
}

